---
 
- name: eclim | Download eclim on 'master' if we don't have it
  connection: local
  get_url: url={{eclim_url}}  dest={{ cur_dir }}/{{ eclim_name }} force=no validate_certs=no

- name: eclim | Install eclim into eclipse
  shell: java -Dvim.files={{ home }}/.vim -Declipse.home={{eclipse_link_base_dir}}/eclipse-{{eclipse_major}} -jar {{ eclim_name }} install 
  args:
     creates: "{{eclipse_link_base_dir}}/eclipse-{{eclipse_major}}/plugins/eclim_{{ eclim_version }}"

- name: eclim | Create shell script to start eclim
  shell: echo "DISPLAY=:1 {{eclipse_link_base_dir}}/eclipse-{{eclipse_major}}/eclimd -b" > start_eclim.sh ; chmod +x start_eclim.sh
  args:
     creates: start_eclim.sh
  
- name: eclim | Create shell script to start headless x
  shell: echo "Xvfb :1 -screen 0 1024x768x24 &" > start_headless.sh ; chmod +x start_headless.sh
  args:
     creates: start_headless.sh
  
